"""baseline — 現有全部 46 張表的完整 schema(自 model metadata autogenerate)。

注意:
* 本 baseline 與 init_db()(create_all + 全部 _migrate_*)產出的 schema 逐欄位
  等價(已以 PRAGMA table_info 全表比對驗證)。
* 由手寫遷移升上來的 legacy DB,索引「名稱」可能與本檔不同(如 ix_lcfg_lbuid);
  ops/migrate 對 legacy DB 走 stamp(不重跑 DDL),Alembic 不校驗現況,
  僅未來 revision 不可引用 legacy 索引名。

Revision ID: 3a4af702fa42
Revises: 
Create Date: 2026-07-04 13:14:25.123165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a4af702fa42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('store_type', sa.String(length=32), nullable=True),
    sa.Column('ics_token', sa.String(length=64), nullable=True),
    sa.Column('reminder_hours_before', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ics_token')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=True)

    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period', name='uq_usage_tenant_period')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('booking_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('points_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tier', sa.String(length=16), server_default='regular', nullable=False),
    sa.Column('ics_token', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ics_token'),
    sa.UniqueConstraint('tenant_id', 'line_user_id', name='uq_booking_customer')
    )
    with op.batch_alter_table('booking_customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_customers_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_customers_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_customers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Taipei', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_locations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_service_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_service_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_service_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default=sa.text('(60)'), nullable=False),
    sa.Column('price_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_services_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_services_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('walkin_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('booked_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slot_start', name='uq_booking_slot_start')
    )
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_slots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_slots_slot_start'), ['slot_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_slots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('business_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('banner_url', sa.String(length=512), nullable=True),
    sa.Column('theme_color', sa.String(length=16), nullable=True),
    sa.Column('social_links', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=256), nullable=True),
    sa.Column('seo_description', sa.String(length=512), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('announcement', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_profiles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_business_profiles_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('min_spend_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redeemed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_coupon_tenant_code')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_customer_tag_name')
    )
    with op.batch_alter_table('customer_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_tags_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('faq_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faq_entries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feature_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('merchant_trade_no', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('period_amount_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('period_type', sa.String(length=1), server_default='M', nullable=False),
    sa.Column('frequency', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('exec_times', sa.Integer(), server_default=sa.text('(99)'), nullable=False),
    sa.Column('total_success_times', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('gwsr', sa.String(length=64), nullable=True),
    sa.Column('auth_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_charged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_subscriptions_merchant_trade_no'), ['merchant_trade_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_feature_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('flex_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flex_menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flex_menus_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flex_menus_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('line_channel_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('channel_secret_enc', sa.LargeBinary(), nullable=False),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('line_bot_user_id', sa.String(length=64), nullable=True),
    sa.Column('credential_status', sa.String(length=16), nullable=True),
    sa.Column('credential_last_error', sa.String(length=255), nullable=True),
    sa.Column('credential_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_target_lang', sa.String(length=16), nullable=False),
    sa.Column('bot_mode', sa.String(length=16), server_default='translation', nullable=False),
    sa.Column('rich_menu_id', sa.String(length=64), nullable=True),
    sa.Column('rich_menu_template', sa.String(length=32), nullable=True),
    sa.Column('rich_menu_theme', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_channel_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_channel_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_channel_configs_line_bot_user_id'), ['line_bot_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_line_channel_configs_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('line_user_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'line_user_id', name='uq_line_user_lang')
    )
    with op.batch_alter_table('line_user_languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_user_languages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_languages_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_user_languages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('line_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('webhook_event_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('last_stage', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'webhook_event_id', name='uq_line_webhook_events_tenant_event')
    )
    with op.batch_alter_table('line_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_webhook_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_webhook_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_webhook_events_webhook_event_id'), ['webhook_event_id'], unique=False)

    op.create_table('marketing_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('schedule_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('segment_json', sa.Text(), nullable=True),
    sa.Column('reward_type', sa.String(length=8), nullable=True),
    sa.Column('reward_value', sa.Integer(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_campaigns_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pii_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pii_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pii_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pii_requests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pii_requests_token'), ['token'], unique=True)

    op.create_table('portfolio_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='TWD', nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('push_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period', name='uq_push_usage')
    )
    with op.batch_alter_table('push_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_usage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_usage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=16), nullable=True),
    sa.Column('oauth_subject', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('auto_reply_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('reply_type', sa.String(length=16), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('flex_menu_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("match_type in ('exact', 'prefix', 'contains')", name='ck_auto_reply_rules_match_type'),
    sa.CheckConstraint("reply_type in ('text', 'flex')", name='ck_auto_reply_rules_reply_type'),
    sa.ForeignKeyConstraint(['flex_menu_id'], ['flex_menus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_reply_rules_flex_menu_id'), ['flex_menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auto_reply_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auto_reply_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('line_user_id', sa.String(length=64), nullable=True),
    sa.Column('party_size', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='confirmed', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('customer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['booking_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['booking_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_reservations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservations_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservations_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservations_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservations_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_reservation_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('booking_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('booking_mode', sa.String(length=16), server_default='capacity', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['booking_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    with op.batch_alter_table('booking_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_staff_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_staff_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_staff_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='waiting', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['booking_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'line_user_id', name='uq_waitlist_slot_line_user')
    )
    with op.batch_alter_table('booking_waitlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_waitlist_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_waitlist_entries_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_waitlist_entries_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_waitlist_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_waitlist_entries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('customer_tag_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['booking_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['customer_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'tag_id', name='uq_customer_tag')
    )
    with op.batch_alter_table('customer_tag_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_tag_links_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_tag_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_tag_links_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_tag_links_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feature_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_change_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_change_history_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('flex_menu_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('bg_color', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('action_type', sa.String(length=16), server_default='postback', nullable=False),
    sa.Column('action_data', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['flex_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flex_menu_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flex_menu_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flex_menu_cards_menu_id'), ['menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flex_menu_cards_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('line_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['booking_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_messages_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_messages_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_line_msg_tenant_user', ['tenant_id', 'line_user_id', 'id'], unique=False)

    op.create_table('marketing_campaign_sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=True),
    sa.Column('period_key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('reward_ref', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['booking_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'customer_id', 'period_key', name='uq_campaign_send')
    )
    with op.batch_alter_table('marketing_campaign_sends', schema=None) as batch_op:
        batch_op.create_index('ix_campaign_send_campaign', ['campaign_id', 'period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_campaign_sends_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_campaign_sends_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_campaign_sends_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_campaign_sends_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('line_user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('total_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('coupon_code', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default='TWD', nullable=False),
    sa.Column('merchant_trade_no', sa.String(length=20), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['booking_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_trade_no')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_order_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('plan_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('from_plan', sa.String(length=32), nullable=False),
    sa.Column('to_plan', sa.String(length=32), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_change_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_change_history_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'feature', name='uq_tenant_feature')
    )
    with op.batch_alter_table('tenant_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_features_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_features_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('api_key_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'period', name='uq_api_key_usage_key_period')
    )
    with op.batch_alter_table('api_key_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_usage_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_usage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_usage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('payload_text', sa.Text(), nullable=False),
    sa.Column('send_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['booking_reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'kind', name='uq_booking_notification')
    )
    with op.batch_alter_table('booking_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_booking_notification_status_due', ['status', 'send_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_notifications_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_notifications_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_reservation_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['booking_reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'kind', name='uq_reminder_resv_kind')
    )
    with op.batch_alter_table('booking_reservation_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_reservation_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservation_reminders_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_reservation_reminders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_reminder_status_due', ['status', 'remind_at'], unique=False)

    op.create_table('booking_service_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['booking_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['booking_staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'staff_id', name='uq_service_staff')
    )
    with op.batch_alter_table('booking_service_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_service_staff_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_service_staff_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_service_staff_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_service_staff_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_staff_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='approved', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['booking_staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_staff_leaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_staff_leaves_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_staff_leaves_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_staff_leaves_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('booking_staff_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('rotation', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['booking_staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'weekday', 'start_time', name='uq_staff_shift')
    )
    with op.batch_alter_table('booking_staff_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_staff_shifts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_staff_shifts_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_staff_shifts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['booking_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['booking_reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'line_user_id', name='uq_redemption_coupon_user')
    )
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=128), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['booking_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['booking_reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_customer_id'))

    op.drop_table('point_transactions')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_coupon_id'))

    op.drop_table('coupon_redemptions')
    with op.batch_alter_table('booking_staff_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_staff_shifts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_staff_shifts_staff_id'))
        batch_op.drop_index(batch_op.f('ix_booking_staff_shifts_id'))

    op.drop_table('booking_staff_shifts')
    with op.batch_alter_table('booking_staff_leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_staff_leaves_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_staff_leaves_staff_id'))
        batch_op.drop_index(batch_op.f('ix_booking_staff_leaves_id'))

    op.drop_table('booking_staff_leaves')
    with op.batch_alter_table('booking_service_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_service_staff_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_service_staff_staff_id'))
        batch_op.drop_index(batch_op.f('ix_booking_service_staff_service_id'))
        batch_op.drop_index(batch_op.f('ix_booking_service_staff_id'))

    op.drop_table('booking_service_staff')
    with op.batch_alter_table('booking_reservation_reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_status_due')
        batch_op.drop_index(batch_op.f('ix_booking_reservation_reminders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservation_reminders_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservation_reminders_id'))

    op.drop_table('booking_reservation_reminders')
    with op.batch_alter_table('booking_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_notifications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_notifications_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_booking_notifications_id'))
        batch_op.drop_index('ix_booking_notification_status_due')

    op.drop_table('booking_notifications')
    with op.batch_alter_table('api_key_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_usage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_usage_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_usage_api_key_id'))

    op.drop_table('api_key_usage')
    with op.batch_alter_table('tenant_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_features_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_features_id'))

    op.drop_table('tenant_features')
    with op.batch_alter_table('plan_change_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_change_history_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_plan_change_history_id'))

    op.drop_table('plan_change_history')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_line_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index('ix_order_tenant_status')

    op.drop_table('orders')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    with op.batch_alter_table('marketing_campaign_sends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_campaign_sends_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_campaign_sends_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_campaign_sends_customer_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_campaign_sends_campaign_id'))
        batch_op.drop_index('ix_campaign_send_campaign')

    op.drop_table('marketing_campaign_sends')
    with op.batch_alter_table('line_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_line_msg_tenant_user')
        batch_op.drop_index(batch_op.f('ix_line_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_line_messages_line_user_id'))
        batch_op.drop_index(batch_op.f('ix_line_messages_id'))

    op.drop_table('line_messages')
    with op.batch_alter_table('flex_menu_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flex_menu_cards_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flex_menu_cards_menu_id'))
        batch_op.drop_index(batch_op.f('ix_flex_menu_cards_id'))

    op.drop_table('flex_menu_cards')
    with op.batch_alter_table('feature_change_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_change_history_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_feature_change_history_id'))

    op.drop_table('feature_change_history')
    with op.batch_alter_table('customer_tag_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_tag_links_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_tag_links_tag_id'))
        batch_op.drop_index(batch_op.f('ix_customer_tag_links_id'))
        batch_op.drop_index(batch_op.f('ix_customer_tag_links_customer_id'))

    op.drop_table('customer_tag_links')
    with op.batch_alter_table('booking_waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_waitlist_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_waitlist_entries_status'))
        batch_op.drop_index(batch_op.f('ix_booking_waitlist_entries_slot_id'))
        batch_op.drop_index(batch_op.f('ix_booking_waitlist_entries_line_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_waitlist_entries_id'))

    op.drop_table('booking_waitlist_entries')
    with op.batch_alter_table('booking_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_staff_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_staff_location_id'))
        batch_op.drop_index(batch_op.f('ix_booking_staff_id'))

    op.drop_table('booking_staff')
    with op.batch_alter_table('booking_reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_reservation_tenant_status')
        batch_op.drop_index(batch_op.f('ix_booking_reservations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservations_staff_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservations_slot_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservations_service_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservations_line_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservations_id'))
        batch_op.drop_index(batch_op.f('ix_booking_reservations_customer_id'))

    op.drop_table('booking_reservations')
    with op.batch_alter_table('auto_reply_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auto_reply_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_auto_reply_rules_id'))
        batch_op.drop_index(batch_op.f('ix_auto_reply_rules_flex_menu_id'))

    op.drop_table('auto_reply_rules')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('push_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_usage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_push_usage_id'))

    op.drop_table('push_usage')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_products_id'))

    op.drop_table('products')
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_items_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_items_category_id'))

    op.drop_table('portfolio_items')
    with op.batch_alter_table('portfolio_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_categories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_categories_id'))

    op.drop_table('portfolio_categories')
    with op.batch_alter_table('pii_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pii_requests_token'))
        batch_op.drop_index(batch_op.f('ix_pii_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pii_requests_id'))

    op.drop_table('pii_requests')
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_campaigns_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_campaigns_id'))

    op.drop_table('marketing_campaigns')
    with op.batch_alter_table('line_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_webhook_events_webhook_event_id'))
        batch_op.drop_index(batch_op.f('ix_line_webhook_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_line_webhook_events_id'))

    op.drop_table('line_webhook_events')
    with op.batch_alter_table('line_user_languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_user_languages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_line_user_languages_line_user_id'))
        batch_op.drop_index(batch_op.f('ix_line_user_languages_id'))

    op.drop_table('line_user_languages')
    with op.batch_alter_table('line_channel_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_channel_configs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_line_channel_configs_line_bot_user_id'))
        batch_op.drop_index(batch_op.f('ix_line_channel_configs_id'))

    op.drop_table('line_channel_configs')
    with op.batch_alter_table('flex_menus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flex_menus_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flex_menus_id'))

    op.drop_table('flex_menus')
    with op.batch_alter_table('feature_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_feature_subscriptions_merchant_trade_no'))
        batch_op.drop_index(batch_op.f('ix_feature_subscriptions_id'))

    op.drop_table('feature_subscriptions')
    with op.batch_alter_table('faq_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_faq_entries_id'))

    op.drop_table('faq_entries')
    with op.batch_alter_table('customer_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_tags_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_customer_tags_id'))

    op.drop_table('customer_tags')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_id'))

    op.drop_table('coupons')
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_profiles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_business_profiles_slug'))
        batch_op.drop_index(batch_op.f('ix_business_profiles_id'))

    op.drop_table('business_profiles')
    with op.batch_alter_table('booking_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_slots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_slots_slot_start'))
        batch_op.drop_index(batch_op.f('ix_booking_slots_id'))

    op.drop_table('booking_slots')
    with op.batch_alter_table('booking_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_services_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_services_location_id'))
        batch_op.drop_index(batch_op.f('ix_booking_services_id'))
        batch_op.drop_index(batch_op.f('ix_booking_services_category_id'))

    op.drop_table('booking_services')
    with op.batch_alter_table('booking_service_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_service_categories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_service_categories_id'))

    op.drop_table('booking_service_categories')
    with op.batch_alter_table('booking_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_locations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_locations_id'))

    op.drop_table('booking_locations')
    with op.batch_alter_table('booking_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_customers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_booking_customers_location_id'))
        batch_op.drop_index(batch_op.f('ix_booking_customers_line_user_id'))
        batch_op.drop_index(batch_op.f('ix_booking_customers_id'))

    op.drop_table('booking_customers')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_id'))

    op.drop_table('api_usage')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_name'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
