"""subscription charges — 進階功能訂閱的逐期扣款明細。

Revision ID: 0beebc1cdea4
Revises: 3a4af702fa42
Create Date: 2026-07-04 13:25:10.839666

注意（過渡期冪等守衛）：legacy DB 的收斂路徑（ops/migrate 分支 2）會先跑
legacy_init_db() 的 create_all——它以「當前 metadata」建缺少的表，因此本表
可能已存在；stamp baseline 後 upgrade 到本 revision 時必須 inspect 跳過，
否則撞表。所有「建表」類 revision 在 legacy 路徑退役前都須比照辦理。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0beebc1cdea4'
down_revision: Union[str, None] = '3a4af702fa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 冪等守衛：legacy 收斂路徑的 create_all 可能已建出本表（見 docstring）。
    bind = op.get_bind()
    if sa.inspect(bind).has_table('subscription_charges'):
        return
    op.create_table('subscription_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('gwsr', sa.String(length=64), nullable=True),
    sa.Column('rtn_msg', sa.String(length=255), nullable=True),
    sa.Column('charged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['feature_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_charges_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_charges_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_charges_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_charges_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_charges_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_charges_id'))

    op.drop_table('subscription_charges')
    # ### end Alembic commands ###
