"""customer line_user_id nullable

Revision ID: 213b8a0c5381
Revises: 0beebc1cdea4
Create Date: 2026-07-04 13:35:09.739776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '213b8a0c5381'
down_revision: Union[str, None] = '0beebc1cdea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_customers', schema=None) as batch_op:
        batch_op.alter_column('line_user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_customers', schema=None) as batch_op:
        batch_op.alter_column('line_user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
