"""customer blacklist — 顧客黑名單欄位（upstream PR #58 合併時補的 revision）。

Revision ID: 0262282689e7
Revises: 213b8a0c5381
Create Date: 2026-07-04 13:56:37.093824

注意（過渡期冪等守衛）：legacy DB 收斂路徑會先跑 _migrate_add_customer_blacklist()
補出同名欄位，本 revision 需 inspect 跳過已存在的欄位（比照 0002 的建表守衛）。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0262282689e7'
down_revision: Union[str, None] = '213b8a0c5381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 冪等守衛：legacy 收斂路徑可能已補過欄位（見 docstring）。
    existing = {
        c["name"]
        for c in sa.inspect(op.get_bind()).get_columns("booking_customers")
    }
    with op.batch_alter_table('booking_customers', schema=None) as batch_op:
        if 'blacklisted' not in existing:
            batch_op.add_column(sa.Column('blacklisted', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        if 'blacklist_reason' not in existing:
            batch_op.add_column(sa.Column('blacklist_reason', sa.String(length=255), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_customers', schema=None) as batch_op:
        batch_op.drop_column('blacklist_reason')
        batch_op.drop_column('blacklisted')

    # ### end Alembic commands ###
